In [1]:
import pandas as pd
import numpy as np

In [2]:
df1=pd.read_csv(r"C:\Users\HARISH\OneDrive\Desktop\Global_Ecom_Analytics\3_SQL\data\online_retail_cleaning-2009-2010.csv",encoding='latin1')

C:\Users\HARISH\AppData\Local\Temp\ipykernel_18464\3400100884.py:1: DtypeWarning: Columns (0: Invoice, 1: Transaction_Type, 2: StockCode, 3: Description, 4: InvoiceDate, 5: Customer_Type, 6: Country) have mixed types. Specify dtype option on import or set low_memory=False.
  df1=pd.read_csv(r"C:\Users\HARISH\OneDrive\Desktop\Global_Ecom_Analytics\3_SQL\data\online_retail_cleaning-2009-2010.csv",encoding='latin1')


In [3]:
df2=pd.read_csv(r"C:\Users\HARISH\OneDrive\Desktop\Global_Ecom_Analytics\3_SQL\data\online_retail_cleaning-2010-2011.csv",encoding='latin1')

In [4]:
df1.info()


<class 'pandas.DataFrame'>
RangeIndex: 525461 entries, 0 to 525460
Data columns (total 10 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Invoice           518596 non-null  str    
 1   Transaction_Type  518596 non-null  str    
 2   StockCode         518596 non-null  str    
 3   Description       515668 non-null  str    
 4   Quantity          518596 non-null  float64
 5   InvoiceDate       518596 non-null  str    
 6   Price             518596 non-null  float64
 7   Customer ID       410763 non-null  float64
 8   Customer_Type     518596 non-null  str    
 9   Country           518596 non-null  str    
dtypes: float64(3), str(7)
memory usage: 40.1 MB


In [5]:
df2.info()


<class 'pandas.DataFrame'>
RangeIndex: 541910 entries, 0 to 541909
Data columns (total 10 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Invoice           536642 non-null  str    
 1   Transaction_Type  536642 non-null  str    
 2   StockCode         536642 non-null  str    
 3   Description       535188 non-null  str    
 4   Quantity          536642 non-null  float64
 5   InvoiceDate       536642 non-null  str    
 6   Price             536642 non-null  float64
 7   Customer ID       401605 non-null  float64
 8   Customer_Type     536642 non-null  str    
 9   Country           536642 non-null  str    
dtypes: float64(3), str(7)
memory usage: 41.3 MB


In [6]:
df=pd.concat([df1,df2],ignore_index=True)

In [7]:
df.head()


,Invoice,Transaction_Type,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Customer_Type,Country
0,489434,Sale,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12.0,01-12-2009 07:45,6.95,13085.0,REGISTERED,United Kingdom
1,489434,Sale,79323P,PINK CHERRY LIGHTS,12.0,01-12-2009 07:45,6.75,13085.0,REGISTERED,United Kingdom
2,489434,Sale,79323W,WHITE CHERRY LIGHTS,12.0,01-12-2009 07:45,6.75,13085.0,REGISTERED,United Kingdom
3,489434,Sale,22041,"RECORD FRAME 7"" SINGLE SIZE",48.0,01-12-2009 07:45,2.10,13085.0,REGISTERED,United Kingdom
4,489434,Sale,21232,STRAWBERRY CERAMIC TRINKET BOX,24.0,01-12-2009 07:45,1.25,13085.0,REGISTERED,United Kingdom


In [8]:
df.info()


<class 'pandas.DataFrame'>
RangeIndex: 1067371 entries, 0 to 1067370
Data columns (total 10 columns):
 #   Column            Non-Null Count    Dtype  
---  ------            --------------    -----  
 0   Invoice           1055238 non-null  str    
 1   Transaction_Type  1055238 non-null  str    
 2   StockCode         1055238 non-null  str    
 3   Description       1050856 non-null  str    
 4   Quantity          1055238 non-null  float64
 5   InvoiceDate       1055238 non-null  str    
 6   Price             1055238 non-null  float64
 7   Customer ID       812368 non-null   float64
 8   Customer_Type     1055238 non-null  str    
 9   Country           1055238 non-null  str    
dtypes: float64(3), str(7)
memory usage: 81.4 MB


In [9]:
df.describe()

,Quantity,Price,Customer ID
count,1.055238e+06,1.055238e+06,812368.000000
mean,1.002209e+01,4.673714e+00,15317.796570
std,1.736819e+02,1.242609e+02,1698.113489
min,-8.099500e+04,-5.359436e+04,12346.000000
25%,1.000000e+00,1.250000e+00,13969.000000
50%,3.000000e+00,2.100000e+00,15245.000000
75%,1.000000e+01,4.150000e+00,16794.000000
max,8.099500e+04,3.897000e+04,18287.000000


In [10]:
df.shape

(1067371, 10)

In [11]:
df.columns

Index(['Invoice', 'Transaction_Type', 'StockCode', 'Description', 'Quantity',
       'InvoiceDate', 'Price', 'Customer ID', 'Customer_Type', 'Country'],
      dtype='str')

In [12]:
df.index

RangeIndex(start=0, stop=1067371, step=1)

In [13]:
print("Test")

Test


In [14]:
df.describe()

,Quantity,Price,Customer ID
count,1.055238e+06,1.055238e+06,812368.000000
mean,1.002209e+01,4.673714e+00,15317.796570
std,1.736819e+02,1.242609e+02,1698.113489
min,-8.099500e+04,-5.359436e+04,12346.000000
25%,1.000000e+00,1.250000e+00,13969.000000
50%,3.000000e+00,2.100000e+00,15245.000000
75%,1.000000e+01,4.150000e+00,16794.000000
max,8.099500e+04,3.897000e+04,18287.000000


In [15]:
df.index

RangeIndex(start=0, stop=1067371, step=1)

In [16]:
df[["Quantity","Price"]].head()

,Quantity,Price
0,12.0,6.95
1,12.0,6.75
2,12.0,6.75
3,48.0,2.10
4,24.0,1.25


In [17]:
quantity = df["Quantity"].to_numpy()
price=df["Price"].to_numpy()

In [19]:
quantity.head()

AttributeError: 'numpy.ndarray' object has no attribute 'head'

In [20]:
revenue=quantity*price

In [21]:
revenue[:4]

array([ 83.4,  81. ,  81. , 100.8])

In [24]:
total = np.sum(revenue)

In [25]:
print(total)

nan


In [26]:
np.isnan(revenue).sum()

np.int64(12133)

In [27]:
np.nansum(revenue)

np.float64(19231800.518)

In [29]:
np.isnan(quantity).sum()

np.int64(12133)

In [30]:
np.isnan(price).sum()

np.int64(12133)

In [32]:
df[["Quantity","Price"]].isna().sum()

Quantity    12133
Price       12133
dtype: int64

In [33]:
df[df["Quantity"].isna() & df["Price"].isna()].shape

(12133, 10)

In [34]:
quantity.shape

(1067371,)

In [35]:
quantity.ndim

1

In [36]:
quantity.dtype

dtype('float64')

In [37]:
price.dtype

dtype('float64')

In [38]:
np.sum(quantity)

np.float64(nan)

In [39]:
np.nansum(quantity).sum()

np.float64(10575687.0)

In [41]:
np.mean(quantity)

np.float64(nan)

In [42]:
np.nanmean(quantity)

np.float64(10.022086960477163)

In [43]:
Transaction_Type=np.where(
    quantity>0,
    "Sale",
    "Return"
)

In [44]:
Transaction_Type[:10]

array(['Sale', 'Sale', 'Sale', 'Sale', 'Sale', 'Sale', 'Sale', 'Sale',
       'Sale', 'Sale'], dtype='<U6')

In [45]:
Transaction_Type=="Return"

array([False, False, False, ...,  True,  True,  True], shape=(1067371,))

In [46]:
np.unique(Transaction_Type,return_counts=True)

(array(['Return', 'Sale'], dtype='<U6'), array([  35022, 1032349]))

In [47]:
df["Transaction_Type"]=Transaction_Type

In [48]:
df.columns

Index(['Invoice', 'Transaction_Type', 'StockCode', 'Description', 'Quantity',
       'InvoiceDate', 'Price', 'Customer ID', 'Customer_Type', 'Country'],
      dtype='str')

In [49]:
df["Transaction_Type"].value_counts()

Transaction_Type
Sale      1032349
Return      35022
Name: count, dtype: int64

In [50]:
conditions = [
    quantity>0,
    quantity<0,
    quantity==0
]
choices = [
    "Sale",
    "Return",
    "Zero Quantity"
]


In [51]:
Transaction_Status= np.select(
    conditions,
    choices,
    default="UnKnown"
)

In [53]:
np.unique(Transaction_Status,return_counts=True)

(array(['Return', 'Sale', 'UnKnown'], dtype='<U13'),
 array([  22889, 1032349,   12133]))

In [54]:
np.sum(quantity==0)

np.int64(0)

In [55]:
np.sum(conditions)

np.int64(1055238)

In [56]:
np.sum(quantity<0)

np.int64(22889)

In [57]:
np.nanmean(quantity)

np.float64(10.022086960477163)

In [58]:
np.nanmin(quantity)

np.float64(-80995.0)

In [59]:
np.nanmax(quantity)

np.float64(80995.0)

In [61]:
df[df["Quantity"].isin([-80995,80995])]

,Invoice,Transaction_Type,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Customer_Type,Country
1060621,581483,Sale,23843,"PAPER CRAFT , LITTLE BIRDIE",80995.0,09-12-2011 09:15,2.08,16446.0,REGISTERED,United Kingdom
1060622,C581484,Return,23843,"PAPER CRAFT , LITTLE BIRDIE",-80995.0,09-12-2011 09:27,2.08,16446.0,REGISTERED,United Kingdom


In [62]:
np.nanstd(quantity)

np.float64(173.6818228253457)

In [65]:
np.sum(quantity<0)

np.int64(22889)

In [66]:
np.sum(quantity[quantity<0])

np.float64(-1061934.0)

In [81]:
abs(np.sum(quantity[quantity<0]))

np.float64(1061934.0)

In [70]:
df["Country"].dtype

<StringDtype(storage='python', na_value=nan)>

In [71]:
country=df["Country"].to_numpy(dtype=object)

In [72]:
np.unique(country)

TypeError: '<' not supported between instances of 'float' and 'str'

In [73]:
country=df["Country"].dropna().to_numpy()

In [ ]:
np.unique(country)

array(['Australia', 'Austria', 'Bahrain', 'Belgium', 'Bermuda', 'Brazil',
       'Canada', 'Channel Islands', 'Cyprus', 'Czech Republic', 'Denmark',
       'EIRE', 'European Community', 'Finland', 'France', 'Germany',
       'Greece', 'Hong Kong', 'Iceland', 'Israel', 'Italy', 'Japan',
       'Korea', 'Lebanon', 'Lithuania', 'Malta', 'Netherlands', 'Nigeria',
       'Norway', 'Poland', 'Portugal', 'RSA', 'Saudi Arabia', 'Singapore',
       'Spain', 'Sweden', 'Switzerland', 'Thailand', 'USA',
       'United Arab Emirates', 'United Kingdom', 'Unspecified',
       'West Indies'], dtype=object)

In [77]:
np.unique(country)

array(['Australia', 'Austria', 'Bahrain', 'Belgium', 'Bermuda', 'Brazil',
       'Canada', 'Channel Islands', 'Cyprus', 'Czech Republic', 'Denmark',
       'EIRE', 'European Community', 'Finland', 'France', 'Germany',
       'Greece', 'Hong Kong', 'Iceland', 'Israel', 'Italy', 'Japan',
       'Korea', 'Lebanon', 'Lithuania', 'Malta', 'Netherlands', 'Nigeria',
       'Norway', 'Poland', 'Portugal', 'RSA', 'Saudi Arabia', 'Singapore',
       'Spain', 'Sweden', 'Switzerland', 'Thailand', 'USA',
       'United Arab Emirates', 'United Kingdom', 'Unspecified',
       'West Indies'], dtype=object)

In [78]:
len(np.unique(country))

43

In [79]:
np.unique(country,return_counts=True)

(array(['Australia', 'Austria', 'Bahrain', 'Belgium', 'Bermuda', 'Brazil',
        'Canada', 'Channel Islands', 'Cyprus', 'Czech Republic', 'Denmark',
        'EIRE', 'European Community', 'Finland', 'France', 'Germany',
        'Greece', 'Hong Kong', 'Iceland', 'Israel', 'Italy', 'Japan',
        'Korea', 'Lebanon', 'Lithuania', 'Malta', 'Netherlands', 'Nigeria',
        'Norway', 'Poland', 'Portugal', 'RSA', 'Saudi Arabia', 'Singapore',
        'Spain', 'Sweden', 'Switzerland', 'Thailand', 'USA',
        'United Arab Emirates', 'United Kingdom', 'Unspecified',
        'West Indies'], dtype=object),
 array([  1912,    938,    126,   3122,     34,     94,    228,   1663,
          1157,     30,    817,  17844,     61,   1049,  14296,  17600,
           663,    360,    253,    368,   1532,    582,     63,     58,
           189,    299,   5139,     32,   1455,    535,   2608,    169,
            10,    346,   3799,   1362,   3181,     76,    535,    500,
        969347,    752,     54])

In [85]:
np.argmax(quantity)

np.int64(518596)

In [86]:
df.iloc[np.argmax(quantity)]

Invoice                NaN
Transaction_Type    Return
StockCode              NaN
Description            NaN
Quantity               NaN
InvoiceDate            NaN
Price                  NaN
Customer ID            NaN
Customer_Type          NaN
Country                NaN
Name: 518596, dtype: object

In [87]:
np.nanmax(quantity)

np.float64(80995.0)

In [89]:
df.iloc[np.argmax(quantity)]

Invoice                NaN
Transaction_Type    Return
StockCode              NaN
Description            NaN
Quantity               NaN
InvoiceDate            NaN
Price                  NaN
Customer ID            NaN
Customer_Type          NaN
Country                NaN
Name: 518596, dtype: object

In [90]:
np.nanargmax(quantity)

np.int64(1060621)

In [91]:
df.iloc[np.nanargmax(quantity)]

Invoice                                  581483
Transaction_Type                           Sale
StockCode                                 23843
Description         PAPER CRAFT , LITTLE BIRDIE
Quantity                                80995.0
InvoiceDate                    09-12-2011 09:15
Price                                      2.08
Customer ID                             16446.0
Customer_Type                        REGISTERED
Country                          United Kingdom
Name: 1060621, dtype: object

In [93]:
id=np.nanargmin(quantity)

In [94]:
df.iloc[id]

Invoice                                 C581484
Transaction_Type                         Return
StockCode                                 23843
Description         PAPER CRAFT , LITTLE BIRDIE
Quantity                               -80995.0
InvoiceDate                    09-12-2011 09:27
Price                                      2.08
Customer ID                             16446.0
Customer_Type                        REGISTERED
Country                          United Kingdom
Name: 1060622, dtype: object

In [95]:
np.clip(quantity,-100,100)

array([12., 12., 12., ..., nan, nan, nan], shape=(1067371,))

In [96]:
np.where(np.isnan(quantity))

(array([ 518596,  518597,  518598, ..., 1067368, 1067369, 1067370],
       shape=(12133,)),)

In [97]:
df.iloc[518596]

Invoice                NaN
Transaction_Type    Return
StockCode              NaN
Description            NaN
Quantity               NaN
InvoiceDate            NaN
Price                  NaN
Customer ID            NaN
Customer_Type          NaN
Country                NaN
Name: 518596, dtype: object

In [98]:
df.iloc[1067370]

Invoice                NaN
Transaction_Type    Return
StockCode              NaN
Description            NaN
Quantity               NaN
InvoiceDate            NaN
Price                  NaN
Customer ID            NaN
Customer_Type          NaN
Country                NaN
Name: 1067370, dtype: object

In [100]:
df.columns

Index(['Invoice', 'Transaction_Type', 'StockCode', 'Description', 'Quantity',
       'InvoiceDate', 'Price', 'Customer ID', 'Customer_Type', 'Country'],
      dtype='str')

In [101]:
df["Revenue"]=df["Quantity"]*df["Price"]

In [102]:
df.columns

Index(['Invoice', 'Transaction_Type', 'StockCode', 'Description', 'Quantity',
       'InvoiceDate', 'Price', 'Customer ID', 'Customer_Type', 'Country',
       'Revenue'],
      dtype='str')

In [108]:
top_country=df.groupby("Country")["Revenue"].sum()

In [112]:
Top_10=top_country.sort_values(ascending=False).head(10)

In [113]:
print(Top_10)

Country
United Kingdom    1.632882e+07
EIRE              6.152291e+05
Netherlands       5.485233e+05
Germany           4.174299e+05
France            3.279967e+05
Australia         1.670616e+05
Switzerland       9.970646e+04
Spain             9.180816e+04
Sweden            8.777552e+04
Denmark           6.574109e+04
Name: Revenue, dtype: float64


In [117]:
Top_Products=df.groupby("Description")["Revenue"].sum().sort_values(ascending=False).head(10)

In [118]:
print(Top_Products)

Description
REGENCY CAKESTAND 3 TIER               327345.20
DOTCOM POSTAGE                         322647.47
WHITE HANGING HEART T-LIGHT HOLDER     257192.70
JUMBO BAG RED RETROSPOT                148505.35
PARTY BUNTING                          147870.80
ASSORTED COLOUR BIRD ORNAMENT          131043.74
PAPER CHAIN KIT 50'S CHRISTMAS         121523.49
POSTAGE                                112341.00
CHILLI LIGHTS                           84521.81
ROTATING SILVER ANGELS T-LIGHT HLDR     73745.87
Name: Revenue, dtype: float64


In [119]:
df["InvoiceDate"].dtype

<StringDtype(storage='python', na_value=nan)>

In [122]:
df["InvoiceDate"]=pd.to_datetime(df["InvoiceDate"], format=("%d-%m-%Y %H:%M"),errors='coerce')

In [123]:
df["InvoiceDate"].dtype

dtype('<M8[us]')

In [125]:
df["Month"]=df['InvoiceDate'].dt.to_period("M")

In [128]:
df.groupby("Month")["Revenue"].sum().head(10)

Month
2009-12    796648.500
2010-01    622479.502
2010-02    531265.366
2010-03    763247.241
2010-04    587926.692
2010-05    613270.720
2010-06    677073.870
2010-07    573333.690
2010-08    654774.390
2010-09    851105.961
Freq: M, Name: Revenue, dtype: float64

In [130]:
top_10_customers=df.groupby("Customer ID")["Revenue"].sum().sort_values(ascending=False).head(10)

In [131]:
print(top_10_customers)

Customer ID
18102.0    598215.22
14646.0    523342.07
14156.0    296378.14
14911.0    270169.49
17450.0    233419.39
13694.0    190862.96
17511.0    171885.98
12415.0    143269.29
16684.0    141502.25
15061.0    136391.48
Name: Revenue, dtype: float64


In [134]:
Revenue_by_Customer_Type=df.groupby("Customer_Type")["Revenue"].sum()

In [135]:
print(Revenue_by_Customer_Type)

Customer_Type
GUEST         2.638408e+06
REGISTERED    1.659339e+07
Name: Revenue, dtype: float64


In [137]:
Top_10_countries_by_quantity=df.groupby("Country")["Quantity"].sum().sort_values(ascending=False).head(10)

In [138]:
print(Top_10_countries_by_quantity)

Country
United Kingdom    8660900.0
Netherlands        381950.0
EIRE               331154.0
Denmark            235218.0
Germany            224367.0
France             184756.0
Australia          103696.0
Sweden              87858.0
Switzerland         52366.0
Spain               45134.0
Name: Quantity, dtype: float64


In [139]:
No_of_orders_by_countries=df.groupby("Country")["Invoice"].nunique().sort_values(ascending=False).head(10)

In [140]:
print(No_of_orders_by_countries)

Country
United Kingdom    49108
Germany            1095
EIRE                806
France              746
Netherlands         250
Spain               188
Belgium             183
Sweden              129
Portugal            124
Switzerland         123
Name: Invoice, dtype: int64


In [141]:
top_10_products_by_quantity_sold=df.groupby("Description")['Quantity'].sum().sort_values(ascending=False).head(10)

In [142]:
print(top_10_products_by_quantity_sold)

Description
WORLD WAR 2 GLIDERS ASSTD DESIGNS     108305.0
WHITE HANGING HEART T-LIGHT HOLDER     92930.0
ASSORTED COLOUR BIRD ORNAMENT          81087.0
JUMBO BAG RED RETROSPOT                77928.0
BROCADE RING PURSE                     70664.0
PACK OF 60 PINK PAISLEY CAKE CASES     56406.0
60 TEATIME FAIRY CAKE CASES            54187.0
SMALL POPCORN HOLDER                   49590.0
PACK OF 72 RETROSPOT CAKE CASES        49283.0
PACK OF 72 RETRO SPOT CAKE CASES       46079.0
Name: Quantity, dtype: float64


In [143]:
df[df["Description"].str.contains(
    "PACK OF 72 RETRO", 
    case=False, 
    na=False
)][["StockCode", "Description"]].drop_duplicates()


,StockCode,Description
246,21212,PACK OF 72 RETRO SPOT CAKE CASES
349051,21212,PACK OF 72 RETROSPOT CAKE CASES


In [144]:
avg_price_by_counry=df.groupby("Country")["Price"].mean()

In [145]:
print(avg_price_by_counry)

Country
Australia                4.238661
Austria                  4.460896
Bahrain                  3.488016
Belgium                  4.728901
Bermuda                  2.491176
Brazil                   2.726702
Canada                   4.640746
Channel Islands          5.445069
Cyprus                   5.419118
Czech Republic           2.938333
Denmark                  2.934994
EIRE                     7.018022
European Community       4.820492
Finland                  4.990095
France                   4.697497
Germany                  3.835424
Greece                   3.922670
Hong Kong               58.166056
Iceland                  2.546087
Israel                   3.580489
Italy                    5.533721
Japan                    2.162560
Korea                    2.384762
Lebanon                  6.182931
Lithuania                2.615926
Malta                   21.991940
Netherlands              3.047593
Nigeria                  3.415000
Norway                  28.267979
Poland

In [146]:
rev_by_country_customertype=df.groupby(
    ['Country','Customer_Type']
)["Revenue"].sum()

In [147]:
print(rev_by_country_customertype)

Country               Customer_Type
Australia             REGISTERED       1.670616e+05
Austria               REGISTERED       2.317760e+04
Bahrain               GUEST            1.507180e+03
                      REGISTERED       1.354370e+03
Belgium               REGISTERED       6.355499e+04
Bermuda               GUEST            1.253140e+03
Brazil                REGISTERED       1.411870e+03
Canada                REGISTERED       4.883040e+03
Channel Islands       REGISTERED       4.144371e+04
Cyprus                REGISTERED       2.403256e+04
Czech Republic        REGISTERED       7.077200e+02
Denmark               REGISTERED       6.574109e+04
EIRE                  GUEST            3.699302e+04
                      REGISTERED       5.782360e+05
European Community    REGISTERED       1.291750e+03
Finland               REGISTERED       2.951445e+04
France                GUEST            1.687130e+03
                      REGISTERED       3.263095e+05
Germany               REGIST

In [150]:
df['Revenue_Rank']=df["Revenue"].rank(ascending=False)

In [151]:
df['Revenue_Rank']

0           32258.0
1           35192.5
2           35192.5
3           26564.5
4          119684.5
             ...   
1067366         NaN
1067367         NaN
1067368         NaN
1067369         NaN
1067370         NaN
Name: Revenue_Rank, Length: 1067371, dtype: float64

In [152]:
df[["Revenue", "Revenue_Rank"]].head(10)

,Revenue,Revenue_Rank
0,83.4,32258.0
1,81.0,35192.5
2,81.0,35192.5
3,100.8,26564.5
4,30.0,119684.5
5,39.6,82731.5
6,30.0,119684.5
7,59.5,53288.0
8,30.6,111656.0
9,45.0,70473.5


In [ ]:
df[["Invoice", "Description", "Revenue", "Revenue_Rank"]].sort_values(
    "Revenue_Rank").head(10)

,Invoice,Description,Revenue,Revenue_Rank
1060621,581483,"PAPER CRAFT , LITTLE BIRDIE",168469.60,1.0
586467,541431,MEDIUM CERAMIC TOP STORAGE JAR,77183.60,2.0
746277,556444,PICNIC BASKET WICKER 60 PIECES,38970.00,3.0
238929,512771,Manual,25111.09,4.0
426971,530715,ROTATING SILVER ANGELS T-LIGHT HLDR,15818.40,5.0
540218,537632,AMAZON FEE,13541.33,6.5
511151,537632,AMAZON FEE,13541.33,6.5
823106,A563185,Adjust bad debt,11062.06,8.0
133499,502263,Manual,10953.50,9.5
133501,502265,Manual,10953.50,9.5


In [156]:
#It is oberserved that product Description such as AMAZON FEE, Adjust bad debt, Manual are not products
# for now , I'm keeping them for furthur analysis and for financial analysis this could be useful and for product
# analysis I think I should other alternate method 

In [157]:
#I'm thinking to filter those non products out ...let me give a try

In [158]:
non_product = [
    "AMAZON FEE",
    "Adjust bad debt",
    "Manual",
    "POSTAGE",
    "DOTCOM POSTAGE",
    "Discount"
]

In [162]:
product_df = df[~df["Description"].isin(non_product)]#~used for opp of isin i.e., notin

In [163]:
df[df["Quantity"]>0]&df.groupby("Customer_Type")["Revenue"].mean()

TypeError: unsupported operand type(s) for &: 'str' and 'float'

In [164]:
pos_df=df[df["Quantity"]>0]

In [165]:
pos_df.groupby("Customer_Type")["Revenue"].mean()

Customer_Type
GUEST         12.86354
REGISTERED    22.28286
Name: Revenue, dtype: float64

In [166]:
df["Transaction_Type"].value_counts()

Transaction_Type
Sale      1032349
Return      35022
Name: count, dtype: int64

In [167]:
df[(df["Quantity"]>10)&(df["Price"]>5)][["Invoice","Description","Quantity","Price","Revenue"]]

,Invoice,Description,Quantity,Price,Revenue
0,489434,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12.0,6.95,83.40
1,489434,PINK CHERRY LIGHTS,12.0,6.75,81.00
2,489434,WHITE CHERRY LIGHTS,12.0,6.75,81.00
13,489436,LOVE BUILDING BLOCK WORD,18.0,5.45,98.10
67,489438,CHARLIE + LOLA BISCUITS TINS,60.0,6.38,382.80
...,...,...,...,...,...
1061513,581497,HOT WATER BOTTLE KEEP CALM,36.0,8.29,298.44
1061520,581497,KNITTED UNION FLAG HOT WATER BOTTLE,11.0,8.29,91.19
1061584,581498,PAPER CHAIN KIT 50'S CHRISTMAS,52.0,5.79,301.08
1061645,581498,RECIPE BOX PANTRY YELLOW DESIGN,11.0,5.79,63.69
